### ISSUE TITLE
Delete a user?

### ISSUE THREAD

**Issue by imangm** [Fab1en/rocket-chat-rest-client#2]
Hi there,

Thank you for your great work. It's very helpful... By the way, I hope it doesn't look so stupid but I can't delete or get information about a user... Not sure what I'm doing wrong... Would you please help, me?

I've tried these codes but without any success:

```
	$sampleuser = new \RocketChat\User('guest-9', '', array(
			'id' => 'HzEmdkKJF2qZHR7K3'
	));
	$sampleuser->info();
```

I've also tried this one:

```
	$sampleuser = new \RocketChat\User(array(
			'id' => 'HzEmdkKJF2qZHR7K3'
	));
	$sampleuser->info();
```

and this one:

```
	$sampleuser = new \RocketChat\User('guest-9', 'HzEmdkKJF2qZHR7K3');
	$sampleuser->info();
```

Thank you very much...

Cheers,
Iman

P.S. The error message I'm getting is:

`The required "userId" or "username" param was not provided [error-user-param-not-provided]`

**Comment by Fab1en** [comment]
Hi @imangm 
Sorry if this is a little confusing.
First, you have to login as an admin user who has the rights to delete other users : 
```
$admin = new \RocketChat\User('my-admin-name', 'my-admin-password');
if( $admin->login() ) {
    echo "admin user logged in\n";
};
```
Then, you create the User object in PHP (this will not generate any API call), and then call the `info` method to fetch its userId (which is different from its username).
```
$user_to_delete = new \RocketChat\User('toDelete', 'toDeletePassword');
$user_to_delete->info();
```
Finally, you can delete the user : 
```
$user_to_delete->delete();
```

The API has now been changed so that the username can be used instead of the userId to delete a user, but I haven't changed my code yet to take that into account.

**Comment by imangm** [comment]
Thanks @Fab1en for your help.

By the way, I wasn't able to make it work... After successful login via an admin account, I run this code:

```
$user_to_delete = new \RocketChat\User('testuser', 'REALPASSWORD');
$user_to_delete->info();
```

and it returns: 

> The required "userId" or "username" param was not provided [error-user-param-not-provided] 

When I run `var_dump($user_to_delete);` it returns:

```
object(RocketChat\User)#8 (6) { ["username"]=> string(8) "testuser" ["password":"RocketChat\User":private]=> string(12) "REALPASSWORD" ["id"]=> NULL ["nickname"]=> NULL ["email"]=> NULL ["api"]=> string(33) "http://my_vps_ip/api/v1/" }
```

I'm not sure what I'm doing wrong...

And another question... Should I know the password of the user which I'm gonna remove it? What if I don't have the password?

Thanks a lot again
