### ISSUE TITLE
postMessage

### ISSUE THREAD

**Issue by tmtben** [Fab1en/rocket-chat-rest-client#3]
Hi,

I don't manage to post a message in a channel.

Please could you give me an example ?

Thanks,
Ben

**Comment by Fab1en** [comment]
Hi Ben
I have added an example [in the README file](https://github.com/Fab1en/rocket-chat-rest-client/blob/master/README.md#post-a-message). Does that help ?

**Comment by tmtben** [comment]
Thanks!
I was trying to call $channel->info() and got this error:
The parameter "roomId" is required [error-roomid-param-not-provided]
